name: gsl_model
channels: 
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.1
  - jupyterlab=3.6.3
  - pandas=1.5.3
  - pyyaml=6.0
  - matplotlib=3.7.1
  - bokeh=3.1.0
  - seaborn=0.12.2
  - pingouin=0.5.3
  - numba=0.56.4
  - pytest=7.3.1
  - requests=2.28.2
  - xlrd=2.0.1
  - pip:
    - netron==6.8.2
    - tsfel==0.1.5
    - tensorflow==2.12.0
    - edgeimpulse==1.0.3
    - edgeimpulse-api==1.22.2
    - wandb==0.14.2 